# VISUALIZATION OF CORONA SPREAD IN INDIA BETWEEN 1-MAY-2020 TO 2- JUNE-2020 USING CHOROPLETH AND BARPLOTS

In [2]:
import os
from datetime import datetime
import time as t
import selenium.webdriver
from datetime import *
import imageio
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

Data downloaded from https://www.kaggle.com/sudalairajkumar/covid19-in-india

In [3]:
import pandas as pd
import numpy as np
import folium
data=pd.read_csv("covid_19_india.csv")
data.head(15)

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
0,1,30/01/20,6:00 PM,Kerala,1,0,0,0,1
1,2,31/01/20,6:00 PM,Kerala,1,0,0,0,1
2,3,01/02/20,6:00 PM,Kerala,2,0,0,0,2
3,4,02/02/20,6:00 PM,Kerala,3,0,0,0,3
4,5,03/02/20,6:00 PM,Kerala,3,0,0,0,3
5,6,04/02/20,6:00 PM,Kerala,3,0,0,0,3
6,7,05/02/20,6:00 PM,Kerala,3,0,0,0,3
7,8,06/02/20,6:00 PM,Kerala,3,0,0,0,3
8,9,07/02/20,6:00 PM,Kerala,3,0,0,0,3
9,10,08/02/20,6:00 PM,Kerala,3,0,0,0,3
10,11,09/02/20,6:00 PM,Kerala,3,0,0,0,3
11,12,10/02/20,6:00 PM,Kerala,3,0,0,0,3
12,13,11/02/20,6:00 PM,Kerala,3,0,0,0,3
13,14,12/02/20,6:00 PM,Kerala,3,0,0,0,3
14,15,13/02/20,6:00 PM,Kerala,3,0,0,0,3

Grouped States/UT on each Dates based on total Confirmed cases of each day<br>
Changed format of date to required format and sorted dataframe according to date

In [4]:
gp_date=data.groupby(["Date","State/UnionTerritory"])["Confirmed"].agg("sum")
gp_date=pd.DataFrame(gp_date)
gp_date=gp_date.reset_index()
gp_date["Date"]=pd.to_datetime(gp_date["Date"], format='%d/%m/%y')
gp_date=gp_date.sort_values("Date")
gp_date=gp_date.reset_index(drop=True)
gp_date

           Date              State/UnionTerritory  Confirmed
0    2020-01-30                            Kerala          1
1    2020-01-31                            Kerala          1
2    2020-02-01                            Kerala          2
3    2020-02-02                            Kerala          3
4    2020-02-03                            Kerala          3
...         ...                               ...        ...
2589 2020-06-02                 Jammu and Kashmir       2601
2590 2020-06-02                         Jharkhand        659
2591 2020-06-02                         Karnataka       3408
2592 2020-06-02                            Ladakh         77
2593 2020-06-02  Cases being reassigned to states       6414

[2594 rows x 3 columns]

india_coord=pd.read_csv("Indian Coordinates.csv")
india_coord.rename(columns={"Name of State / UT":"State/UnionTerritory"},inplace=True)
india_coord.iloc[:,0]=india_coord.iloc[:,0].str.strip()
india_coord.columns.values

In [5]:
gp_date.columns.values

array(['Date', 'State/UnionTerritory', 'Confirmed'], dtype=object)

In [7]:
gp_date['State/UnionTerritory'].replace({'Nagaland#':'Nagaland','Uttarakhand':'Uttaranchal','Odisha':'Orissa',
                                        'Dadar Nagar Haveli':'Dadra and Nagar Haveli','Jharkhand#':'Jharkhand'
                                        ,'Andaman and Nicobar Islands':'Andaman and Nicobar'},inplace=True)

Remove rows where State/UT data is Unassigned

In [8]:
gp_date=gp_date[gp_date['State/UnionTerritory']!='Unassigned']
print(sorted(gp_date['State/UnionTerritory'].unique()))

['Andaman and Nicobar', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Cases being reassigned to states', 'Chandigarh', 'Chhattisgarh', 'Dadra and Nagar Haveli', 'Delhi', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand', 'Karnataka', 'Kerala', 'Ladakh', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Orissa', 'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telengana', 'Tripura', 'Uttar Pradesh', 'Uttaranchal', 'West Bengal']

In [10]:
al=gp_date['State/UnionTerritory'].unique()
print(len(al))

36

out=gp_date.merge(india_coord, on='State/UnionTerritory')

In [11]:
options = webdriver.ChromeOptions()
options.add_argument("--start-maximized")
driver = webdriver.Chrome(executable_path="C:\Python27\Scripts\chromedriver.exe",chrome_options=options)
options.headless = False

C:\Users\hp\anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: use options instead of chrome_options
  This is separate from the ipykernel package so we can avoid doing imports until

In [13]:
dates=gp_date.Date.unique()
dates=dates[92:]
print((dates))
india_geojson = r'india_states.geojson' # geojson file
gp_date["Confirm_log"]=np.log10(gp_date["Confirmed"] + 1)

['2020-05-01T00:00:00.000000000' '2020-05-02T00:00:00.000000000'
 '2020-05-03T00:00:00.000000000' '2020-05-04T00:00:00.000000000'
 '2020-05-05T00:00:00.000000000' '2020-05-06T00:00:00.000000000'
 '2020-05-07T00:00:00.000000000' '2020-05-08T00:00:00.000000000'
 '2020-05-09T00:00:00.000000000' '2020-05-10T00:00:00.000000000'
 '2020-05-11T00:00:00.000000000' '2020-05-12T00:00:00.000000000'
 '2020-05-13T00:00:00.000000000' '2020-05-14T00:00:00.000000000'
 '2020-05-15T00:00:00.000000000' '2020-05-16T00:00:00.000000000'
 '2020-05-17T00:00:00.000000000' '2020-05-18T00:00:00.000000000'
 '2020-05-19T00:00:00.000000000' '2020-05-20T00:00:00.000000000'
 '2020-05-21T00:00:00.000000000' '2020-05-22T00:00:00.000000000'
 '2020-05-23T00:00:00.000000000' '2020-05-24T00:00:00.000000000'
 '2020-05-25T00:00:00.000000000' '2020-05-26T00:00:00.000000000'
 '2020-05-27T00:00:00.000000000' '2020-05-28T00:00:00.000000000'
 '2020-05-29T00:00:00.000000000' '2020-05-30T00:00:00.000000000'
 '2020-05-31T00:00:00.000000000' '2020-06-01T00:00:00.000000000'
 '2020-06-02T00:00:00.000000000']

C:\Users\hp\anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [14]:
gp_date[gp_date['Date']==dates[-1]] ##2020 JUNE 2

           Date              State/UnionTerritory  Confirmed  Confirm_log
2558 2020-06-02                           Manipur         83     1.924279
2559 2020-06-02                         Meghalaya         27     1.447158
2560 2020-06-02                           Mizoram          1     0.301030
2561 2020-06-02                          Nagaland         43     1.643453
2562 2020-06-02                            Orissa       2104     3.323252
2563 2020-06-02                        Puducherry         74     1.875061
2564 2020-06-02                            Punjab       2301     3.362105
2565 2020-06-02                         Telengana       2792     3.446071
2566 2020-06-02                            Sikkim          1     0.301030
2567 2020-06-02                        Tamil Nadu      23495     4.370994
2568 2020-06-02                           Tripura        420     2.624282
2569 2020-06-02                     Uttar Pradesh       8075     3.907196
2570 2020-06-02                       Uttaranchal        958     2.981819
2571 2020-06-02                       West Bengal       5772     3.761402
2572 2020-06-02                       Maharashtra      70013     4.845185
2573 2020-06-02                         Rajasthan       8980     3.953325
2574 2020-06-02                    Madhya Pradesh       8283     3.918240
2575 2020-06-02               Andaman and Nicobar         33     1.531479
2576 2020-06-02                            Kerala       1326     3.122871
2577 2020-06-02                    Andhra Pradesh       3783     3.577951
2578 2020-06-02                 Arunachal Pradesh         22     1.361728
2579 2020-06-02                             Assam       1390     3.143327
2580 2020-06-02                             Bihar       3926     3.594061
2581 2020-06-02                        Chandigarh        294     2.469822
2582 2020-06-02                      Chhattisgarh        547     2.738781
2583 2020-06-02            Dadra and Nagar Haveli          3     0.602060
2584 2020-06-02                             Delhi      20834     4.318794
2585 2020-06-02                               Goa         71     1.857332
2586 2020-06-02                           Gujarat      17200     4.235554
2587 2020-06-02                           Haryana       2356     3.372360
2588 2020-06-02                  Himachal Pradesh        340     2.532754
2589 2020-06-02                 Jammu and Kashmir       2601     3.415307
2590 2020-06-02                         Jharkhand        659     2.819544
2591 2020-06-02                         Karnataka       3408     3.532627
2592 2020-06-02                            Ladakh         77     1.892095
2593 2020-06-02  Cases being reassigned to states       6414     3.807197

## CHOROPLETH MAP
Creating subsets of dataframe for each year <br>
Creating a Terrain map of Indian Map using folium <br>
On to which colors are specified based on the Confirm_log attribute on each State/Union Territory<br>
File is then saved appending with the current timestamp

In [ ]:
for date in dates:
    temp=gp_date[gp_date['Date']==date]
    t= pd.to_datetime(str(date)) 
    timestring = t.strftime('%d %B, %Y')
    india_map = folium.Map(location=[21.6937, 78.9629],zoom_start=5, tiles='Stamen Toner',height=655)
    india_map.choropleth(
    geo_data=india_geojson,
    threshold_scale=[0, 1, 2, 3,4 ,6],
    data=temp,
    columns=['State/UnionTerritory', 'Confirm_log'],
    key_on='feature.properties.NAME_1',
    fill_color='YlOrRd',
    legend_name=timestring,
    )
    india_map.save('map.html')
    driver.get('file:///F:/pY/Exp/map.html')
    now = datetime.now()
    hms=now.strftime("%H_%M_%S")
    driver.save_screenshot("covidImage.png")
    os.rename('covidImage.png', "covidImage"+hms+".png")

In [87]:
path = "F:/pY/Exp/"
image_folder = os.fsencode(path)

filenames = []

for file in os.listdir(image_folder):
    filename = os.fsdecode(file)
    if filename.endswith( ('.png') ):
        filenames.append(filename)

filenames.sort()
images = list(map(lambda filename: imageio.imread(filename), filenames))
imageio.mimsave(os.path.join('covid2_zoom5.gif'), images, duration = 0.6)

![SegmentLocal](covid2_zoom5.gif "segment")

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
for date in dates:
    plt.figure(figsize=(30,28))
    temp=gp_date[gp_date["Date"]==date]
    t= pd.to_datetime(str(date)) 
    timestring = t.strftime('%d %B, %Y')
    temp.sort_values("State/UnionTerritory",inplace=True)
    sns.set(font_scale=2.4)
    g =sns.barplot(x='Confirmed',y='State/UnionTerritory',data=temp)
    for p in g.patches:
        percentage = int(p.get_width())
        x = p.get_x() + p.get_width() + 4
        y = p.get_y() + p.get_height()/1.4
        g.annotate(percentage, (x, y))
    plt.title(timestring)
    now = datetime.now()
    hms=now.strftime("%H_%M_%S")
    plt.savefig("covid"+hms+".png")

In [52]:
path = "F:/pY/Exp/"
image_folder = os.fsencode(path)

filenames = []

for file in os.listdir(image_folder):
    filename = os.fsdecode(file)
    if filename.endswith( ('.png') ):
        filenames.append(filename)

filenames.sort()
images = list(map(lambda filename: imageio.imread(filename), filenames))
imageio.mimsave(os.path.join('covid_plot.gif'), images, duration = 1.2)

![SegmentLocal](covid_plot.gif "segment")